# Netlify configuration for this Next.js app.
# Keep this file minimal: specify the build command and enable the official Next.js plugin.
# The plugin handles SSR/ISR, redirects, and functions output automatically.

[build]
  # Uses the `build` script from package.json (next build)
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Notes:
# - Do NOT store secrets in this file. Add production environment variables (for example
#   NEXT_PUBLIC_API_BASE_URL) in the Netlify site Settings > Build & deploy > Environment.
# - If you need a specific Node version, set it via the Netlify UI or add an `engines` field
#   to package.json. Example: "engines": { "node": "18.x" }